name: 'composite-actions'
description: 'setup node and pnpm and install dependencies'

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: 23.7.0
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile