name: Test and Deploy

on: 
  push:
    branches:
      - master

jobs:
  test:
    name: Run Lint And Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 23.7.0
      
      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Tests
        run: pnpm test
  
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 23.7.0
      
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build 
        run: pnpm build:docs

      - name: Upload Docs
        uses: actions/upload-artifact@v6
        with:
          name: docs
          path: ./packages/docs/.vitepress/dist
  
  deploy:
    name: Deploy Docs to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docs
        uses: actions/download-artifact@v5
        with:
          name: docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: .
    
   
